#!/usr/bin/python

import os
import subprocess

from sets import Set

configFileName = "config.ebook"
start_directory = os.getcwd()

ebookRoots = []
for root, dirs, files in os.walk("."):
  if configFileName in files:
    ebookRoots.append(root)

for ebook_root in ebookRoots:
  print ebook_root + "..."
  os.chdir(ebook_root)
  if not os.path.exists("aspell.fr.pws"):
    os.system("echo 'personal_ws-1.1 fr 0 utf-8' > aspell.fr.pws")
  html_files = [f for f in os.listdir("Text") if f.endswith(".html")]
  global_words = Set([])
  local_words = Set([])
  skip_to_next_book = False
  for html_file in html_files:
    if skip_to_next_book:
      break
    words_list = subprocess.check_output([
      "cat Text/" + html_file + " | aspell -l fr --add-extra-dicts ./aspell.fr.pws " + \
      "--add-extra-dicts ./../../aspell.fr.pws --encoding=utf-8 list"], shell=True)

    words = words_list.split("\n")

    word_set = Set([])
    for word in words:
      word_set.add(word)

    for word in word_set:
      word = word.strip()
      if word == "":
        continue
      print "################################################\n"
      os.system("grep -C 2 '" + word + "' Text/" + html_file)
      print "\n################################################\n"
      print word + " -- (Enter, Local or Global, Skip or eXit): ",
      input_variable = raw_input()
      lc_input_variable = input_variable.strip().lower()
      if lc_input_variable == "":
        doNothing = 1
      elif lc_input_variable == "g":
        global_words.add(word)
      elif lc_input_variable == "l":
        local_words.add(word)
      elif lc_input_variable == "s":
        continue
      elif lc_input_variable == "x":
        skip_to_next_book = True
        break
      else:
        # Replacement word
        os.system("sed -i 's|" + word + "|" + input_variable + "|g' Text/" + html_file)

  if len(global_words) != 0:
    global_word_append = "\n".join(global_words) + "\n"
    global_handle = open("./../../aspell.fr.pws", "a")
    global_handle.write(global_word_append)
    global_handle.close()

  if len(local_words) != 0:
    local_word_append = "\n".join(local_words) + "\n"
    local_handle = open("aspell.fr.pws", "a")
    local_handle.write(local_word_append)
    local_handle.close()
  os.chdir(start_directory)
