#!/usr/bin/python

import os
import subprocess

from sets import Set

configFileName = "config.ebook"

ebookRoots = []
for root, dirs, files in os.walk("."):
  if configFileName in files:
    ebookRoots.append(root)

for ebook_root in ebookRoots:
  os.chdir(ebook_root)
  if not os.path.exists("aspell.fr.pws"):
    os.system("echo 'personal_ws-1.1 fr 0 utf-8' > aspell.fr.pws")
  words_list = subprocess.check_output([
    "cat Text/*.html | aspell -l fr --add-extra-dicts ./aspell.fr.pws " + \
    "--add-extra-dicts ./../../aspell.fr.pws --encoding=utf-8 list"], shell=True)

  words = words_list.split("\n")

  word_set = Set([])
  for word in words:
    word_set.add(word)

  global_words = Set([])
  local_words = Set([])
  for word in word_set:
    word = word.strip()
    if word == "":
      continue
    print word + " -- (Enter, Local or Global, or eXit): ",
    input_variable = raw_input()
    lc_input_variable = input_variable.strip().lower()
    if lc_input_variable == "":
      doNothing = 1
    elif lc_input_variable == "g":
      global_words.add(word)
    elif lc_input_variable == "l":
      local_words.add(word)
    elif lc_input_variable == "x":
      break
    else:
      # Replacement word
      os.system("sed -i 's|" + word + "|" + input_variable + "|g' Text/*")

  if len(global_words) != 0:
    global_word_append = "\n".join(global_words) + "\n"
    global_handle = open("./../../aspell.fr.pws", "a")
    global_handle.write(global_word_append)
    global_handle.close()

  if len(local_words) != 0:
    local_word_append = "\n".join(local_words) + "\n"
    local_handle = open("aspell.fr.pws", "a")
    local_handle.write(local_word_append)
    local_handle.close()
