#!/usr/bin/python

import os
import sys

from optparse import OptionParser
from common import mkebook

parser = OptionParser()
parser.add_option("-k", "--kindle", dest="kindle",
                  action="store_true",
                  help="Generate Kindle file")
parser.add_option("-f", "--force", dest="force",
                  action="store_true",
                  help="Force generate output, even if input is older")
parser.add_option("-d", "--debug", dest="debug",
                  action="store_true",
                  help="Enable debug mode.")

(options, args) = parser.parse_args()

if len(args) < 2:
  # No folder given in argument. Use ".".
  cwd = os.path.realpath(".")
else:
  cwd = os.path.realpath(args[1])
configFileName = "config.ebook"
ebookRoots = []

for root, dirs, files in os.walk("."):
  if configFileName in files:
    ebookRoots.append(root)

if len(ebookRoots) == 0:
  print "No ebook to make. Please create a config.ebook file."
  exit(0)

for ebookRoot in ebookRoots:
  os.chdir(ebookRoot)
  mkebook.make_ebook(options, ebookRoot)
  os.system("checkspelling")
  os.chdir(cwd)

print "All up to date."
